[tool.poetry]
name = "introdução"
version = "0.1.0"
description = ""
authors = ["gustavo"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.1"
pydantic = "^2.8.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
